stages:
    - evaluate

run_evaluate:
    image: ubuntu:18.04
    stage: evaluate
    variables:
        trec_eval: 'yes'
    script:
        - apt update && apt install -y build-essential make git
        - git clone https://github.com/usnistgov/trec_eval.git
        - make -j -C trec_eval
        - ./evaluate.sh
    tags:
        - mir
