stages:
    - evaluate

evaluate:
    image: ubuntu:18.04
    stage: prepare_env
    script:
        - apt install -y build-essential make git
        - git clone https://github.com/usnistgov/trec_eval.git
        - make -j -C trec_eval
        - ./evaluate.sh
    tags:
        - submission
